# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'simple-quiz' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for simple-quiz

  target 'simple-quizTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'simple-quizUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'SwiftyJSON'

end
